### ISSUE TITLE
Distance from point to line.

### ISSUE THREAD

**Issue by mario-s** [efrenfuentes/haversine-rs#1]
Hello,

I used your library in a pet project of mine. My use case was to calculate the distance from a point to a line between two coordinates.

I would like to add this feature to your library. What do you think?

Regards,
Mario

**Comment by efrenfuentes** [comment]
Hi @mario-s, sorry for the late answer, I like the idea you can make a pull request if you still interested!

**Comment by mario-s** [comment]
Hola Efrén! 

The task is not as simple as I thought.

My first attempt was quite short and easy to understand. Then I came across a thread where people discussed a similar topic: https://sourceforge.net/p/geographiclib/discussion/1026621/thread/21aaff9f/ 

In the discussion is a Python example which can be easily translated to Rust. This example uses a library which also exists in Rust. If I would add the feature to your library then I also need this extra library. That bloats your lib a lot, which I can't recommend for something that might be used by few users.

I close this issue.

Regards
Mario
